---
- name: Install utilities
  yum:
    name: unzip
  become: yes

- name: Create temporary download directory
  file:
    path: "{{ packer_tmp_download_dir }}"
    state: directory

- name: Download packer
  unarchive:
    src: "{{ packer_download_url }}"
    dest: "{{ packer_tmp_download_dir }}"
    remote_src: yes

- name: Copy binary to bin directory
  copy:
    remote_src: yes
    src: "{{ packer_tmp_download_dir }}/packer"
    dest: "{{ packer_bin_path }}/packer.io"
    owner: root
    group: root
    mode: 0755
  become: yes
