---
- name: Install utilities
  yum:
    name: unzip
  become: yes

- name: create temporary download directory
  tempfile:
    state: directory
  register: temp_download_dir
  notify: "cleanup temp download directory"

- name: Download packer
  unarchive:
    src: "{{ packer_download_url }}"
    dest: "{{ temp_download_dir.path }}"
    remote_src: yes

- name: Copy binary to bin directory
  copy:
    remote_src: yes
    src: "{{ temp_download_dir.path }}/packer"
    dest: "{{ packer_bin_path }}/packer.io"
    owner: root
    group: root
    mode: 0755
  become: yes
